# VARIABLES
# ---------
name:           sbin.dk
url:            http://sbin.dk
description:    "Personal english blog of a french web developer in Copenhagen from South Korea :)"
keywords:       "PHP5, Symfony2, MySQL, NoSQL, jQuery, NodeJS, LESS, NginX, HTML5, CSS3, Linux, Debian, Ubuntu Server, Mac OS X"
rss:            "sbin.dk blog feed"
author:         Antoine Corcy
email:          contact@sbin.dk
# ---------
about:          http://about.me/antoinecorcy
github:         https://github.com/toin0u
githubsource:   https://github.com/toin0u/sbin.dk
twitter:        https://twitter.com/toin0u
googleplus:     https://plus.google.com/100161090014693834503/
linkedin:       http://linkd.in/corcya
symfony:        https://connect.sensiolabs.com/profile/toin0u
facebook:       https://facebook.com/toin0u
tumblr:         http://tumblr.sbin.dk/
lastfm:         http://last.fm/user/ackorea
pinterest:      https://pinterest.com/toin0u/
# ---------
ga:             UA-31694981-1
summary:        true
# ---------
disqus_id:      sbindk
disqus_dev:     0
# ---------
pinterest_id:   30e5c3076a99a3bf6feb53b72867155c


# JEKYLL
# ---------
exclude:        [README.md, Rakefile]
permalink:      /:year/:month/:day/:title/
pygments:       true
paginate:       5
markdown:       rdiscount


# PLUGINS
# -------
lessc:          lessc --yui-compress
redirects:      yes