# VARIABLES
# ---------
name:           sbin.dk
url:            http://sbin.dk
description:    "Personal blog of a web developer in Copenhagen"
keywords:       "PHP5, Symfony2, SQL, NoSQL, jQuery, NodeJS, LESS, NginX, HTML5, CSS3, Debian, Ubuntu, Mac OS X"
rss:            "sbin.dk blog feed"
author:         Antoine Corcy
email:          contact@sbin.dk
copyright:      "&copy; 2012"
# ---------
github:         https://github.com/toin0u
githubsource:   https://github.com/toin0u/sbin.dk
twitter:        https://twitter.com/toin0u
googleplus:     https://plus.google.com/100161090014693834503/
linkedin:       http://www.linkedin.com/
facebook:       https://facebook.com/toin0u
tumblr:         http://dkfr.tumblr.com/
lastfm:         http://last.fm/user/ackorea
# ---------
ga:             UA-31694981-1


# JEKYLL
# ---------
permalink:      /:year/:month/:day/:title/
pygments:       true
paginate:       3
markdown:       rdiscount


# PLUGINS
# -------
lessc:          lessc --yui-compress